# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoBufRFP.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProtoBufRFP.proto',
  package='ass1',
  syntax='proto2',
  serialized_pb=_b('\n\x11ProtoBufRFP.proto\x12\x04\x61ss1\":\n\x0bProtoBufRFP\x12\x11\n\tunitPrice\x18\x01 \x02(\t\x12\x18\n\x10validationPeriod\x18\x02 \x02(\t')
)




_PROTOBUFRFP = _descriptor.Descriptor(
  name='ProtoBufRFP',
  full_name='ass1.ProtoBufRFP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unitPrice', full_name='ass1.ProtoBufRFP.unitPrice', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='validationPeriod', full_name='ass1.ProtoBufRFP.validationPeriod', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['ProtoBufRFP'] = _PROTOBUFRFP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoBufRFP = _reflection.GeneratedProtocolMessageType('ProtoBufRFP', (_message.Message,), dict(
  DESCRIPTOR = _PROTOBUFRFP,
  __module__ = 'ProtoBufRFP_pb2'
  # @@protoc_insertion_point(class_scope:ass1.ProtoBufRFP)
  ))
_sym_db.RegisterMessage(ProtoBufRFP)


# @@protoc_insertion_point(module_scope)
