# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoBufRFQ.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProtoBufRFQ.proto',
  package='ass1',
  syntax='proto2',
  serialized_pb=_b('\n\x11ProtoBufRFQ.proto\x12\x04\x61ss1\"f\n\x0bProtoBufRFQ\x12\r\n\x05rfqId\x18\x01 \x02(\t\x12\x0e\n\x06\x61\x63\x63tId\x18\x02 \x02(\t\x12\x12\n\nproductNum\x18\x03 \x02(\t\x12\x12\n\nproductCat\x18\x04 \x02(\t\x12\x10\n\x08quantity\x18\x05 \x02(\t')
)




_PROTOBUFRFQ = _descriptor.Descriptor(
  name='ProtoBufRFQ',
  full_name='ass1.ProtoBufRFQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfqId', full_name='ass1.ProtoBufRFQ.rfqId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acctId', full_name='ass1.ProtoBufRFQ.acctId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='productNum', full_name='ass1.ProtoBufRFQ.productNum', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='productCat', full_name='ass1.ProtoBufRFQ.productCat', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='ass1.ProtoBufRFQ.quantity', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['ProtoBufRFQ'] = _PROTOBUFRFQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoBufRFQ = _reflection.GeneratedProtocolMessageType('ProtoBufRFQ', (_message.Message,), dict(
  DESCRIPTOR = _PROTOBUFRFQ,
  __module__ = 'ProtoBufRFQ_pb2'
  # @@protoc_insertion_point(class_scope:ass1.ProtoBufRFQ)
  ))
_sym_db.RegisterMessage(ProtoBufRFQ)


# @@protoc_insertion_point(module_scope)
